defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# hydra settings
hydra:
  mode: RunMode.RUN
  run:
    dir: outputs/${experiment_name}/${method_name}/${now:%Y-%m-%d_%H%M%S}
  job:
    chdir: True

config: DefaultConfig