defaults:
  - graph_default
  - _self_

method_name: mipnerf

# Differences compared to paper
#       This repo                         mipNeRF
# density = softplus(x)          density = softplus(x-1)
# rgb = sigmoid(x)               rgb = (1 + 2e) / (1 + exp(-x)) -e

graph:
  _target_: pyrad.graphs.mipnerf.MipNerfGraph
  num_coarse_samples: 128
  num_importance_samples: 128
  loss_coefficients:
    rgb_loss_coarse: 0.1
    rgb_loss_fine: 1.0

data:
  # Train dataloading.
  dataloader_train:
    _target_: pyrad.data.dataloader.TrainDataloader
    image_sampler:
      _target_: pyrad.data.image_sampler.CacheImageSampler
      num_images_to_sample_from: 0
      num_times_to_repeat_images: -1
