defaults:
  - graph_default
  - _self_

method_name: tensorf

viewer:
  enable: false
  num_rays_per_chunk: 16384

pipeline:
  dataloader:
    train_dataset:
      _target_: nerfactory.dataloaders.datasets.Blender
      data_directory: data/blender/lego
      alpha_color: white
      downscale_factor: 1
    train_num_rays_per_batch: 1600
    eval_num_rays_per_chunk: 2400
  model:
    _target_: nerfactory.models.tensorf.TensoRFModel
    loss_coefficients:
      rgb_loss: 1.0
      feature_loss: 8e-5

optimizers:
  fields:
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.001
    scheduler:
      _target_: nerfactory.optimizers.optimizers.ExponentialDecaySchedule
      lr_final: 0.00005
      max_steps: 15000
  position_encoding:
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.02
    scheduler:
      _target_: nerfactory.optimizers.optimizers.ExponentialDecaySchedule
      lr_final: 0.005
      max_steps: 15000
  direction_encoding:
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.02
    scheduler:
      _target_: nerfactory.optimizers.optimizers.ExponentialDecaySchedule
      lr_final: 0.005
      max_steps: 15000
