defaults:
  - graph_default
  - _self_

data:
  # Train dataloading.
  dataset_inputs_train:
    _target_: nerfactory.data.datasets.Blender
    data_directory: data/blender/lego
    downscale_factor: 1
  # Eval dataloading
  dataset_inputs_eval:
    _target_: nerfactory.data.datasets.Blender
    data_directory: data/blender/lego
    downscale_factor: 1
