defaults:
  - graph_default
  - _self_

method_name: tensorf

viewer:
  enable: false
  num_rays_per_chunk: 16384

data:
  # Train dataloading.
  dataset_inputs_train:
    _target_: nerfactory.data.datasets.Blender
    data_directory: data/blender/lego
    alpha_color: white
    downscale_factor: 1
  dataloader_train:
    pixel_sampler:
      num_rays_per_batch: 1600 # for training
  # Eval dataloading
  dataset_inputs_eval:
    _target_: nerfactory.data.datasets.Blender
    data_directory: data/blender/lego
    alpha_color: white
    downscale_factor: 1
  dataloader_eval:
    num_rays_per_chunk: 2400 # all rays for evaluation

graph:
  _target_: nerfactory.graphs.tensorf.TensoRFGraph
  enable_collider: True
  collider_config:
    _target_: nerfactory.graphs.modules.scene_colliders.NearFarCollider
    near_plane: 2.0
    far_plane: 6.0
  num_coarse_samples: 64
  num_importance_samples: 128
  loss_coefficients:
    rgb_loss: 1.0
  enable_density_field: false
  density_field_config:
    # Please see the docstr for DensityGrid on how to set those arguments.
    _target_: nerfactory.fields.density_fields.density_grid.DensityGrid
    center: 0.0 # simply set it as the center of the scene bbox
    base_scale: 3.0 # simply set it as the scale of the scene bbox
    num_cascades: 1 # if using more than 1 cascade, the `base_scale` can be smaller than scene scale.
    resolution: 128
    update_every_num_iters: 16

optimizers:
  fields:
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.001
    scheduler:
      _target_: nerfactory.optimizers.optimizers.ExponentialDecaySchedule
      lr_final: 0.000005
      max_steps: 1000000
  position_encoding:
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.02
    scheduler:
      _target_: nerfactory.optimizers.optimizers.ExponentialDecaySchedule
      lr_final: 0.000005
      max_steps: 1000000
  direction_encoding:
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.02  
    scheduler:
      _target_: nerfactory.optimizers.optimizers.ExponentialDecaySchedule
      lr_final: 0.000005
      max_steps: 1000000