defaults:
  - graph_default
  - _self_

method_name: instant_ngp
data:
  dataloader_train:
    pixel_sampler:
      num_rays_per_batch: 8192 # for training
  dataloader_eval:
    num_rays_per_chunk: 8192 # for evaluation

viewer:
  enable: true
  num_rays_per_chunk: 16384

graph:
  _target_: pyrad.graphs.instant_ngp.NGPGraph
  collider_config:
    _target_: pyrad.graphs.modules.scene_colliders.AABBBoxCollider
  field_implementation: tcnn # torch, tcnn, ...
  loss_coefficients: # loss coefficients
    rgb_loss: 1.0

# optimizer options for network
optimizers:
  fields:
    optimizer:
      lr: 3e-3
      eps: 1e-15 # NGP prefers small eps
    # Note: If you want slightly faster coverange, you can use the following optimizer instead, which
    # requires to install apex following https://github.com/NVIDIA/apex#linux
    # optimizer:
    #   _target_: apex.optimizers.FusedAdam
    #   lr: 3e-3
    #   eps: 1e-15
    scheduler: null

trainer:
  mixed_precision: true # Stabilizes training when using tcnn
