defaults:
  - instant_ngp
  - _self_
  
method_name: instant_ngp
data:
  pixel_sampler:
    num_rays_per_batch: 4096
  val_downscale_factor: 1
  val_num_rays_per_chunk: 16384
graph:
  network:
    field_implementation: tcnn
  steps_per_test: 10000
