defaults:
  - vanilla_nerf
  - override data/dataset: friends_TBBT-big_living_room
  - _self_

experiment_name: friends_TBBT-big_living_room
method_name: semantic_nerf

data:
  image_dataset:
    # "image", "mask", "semantics"
    _target_: pyrad.nerf.dataset.image_dataset.PanopticImageDataset

graph:
  network:
    _target_: pyrad.nerf.graph.semantic_nerf.SemanticNerfGraph
    collider_config:
      _target_: pyrad.nerf.colliders.AABBBoxCollider
    num_coarse_samples: 64
    num_importance_samples: 64
    loss_coefficients: # loss coefficients
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
      semantic_loss_fine: 0.05
