name: Run prettier for viewer client app.

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  prettier:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettify JS code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write ./pyrad/viewer/app/**/*.{js,md,yaml,json,html,jsx,css,yml}
