name: Build and deploy viewer.

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nerfactory/viewer/app
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
          # cache: 'yarn'

      - name: Install packages
        run: yarn install

      - name: Build project
        run: CI=false yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./nerfactory/viewer/app/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    env:
      SSH_KEY: ${{secrets.SSH_KEY}}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./nerfactory/viewer/app/build

      - run: mkdir ~/.ssh
      - run: 'echo "$SSH_KEY" >> ~/.ssh/github_actions_user_key_filename'
      - run: chmod 400 ~/.ssh/github_actions_user_key_filename
      - run: cat ~/.ssh/github_actions_user_key_filename
      - run: echo -e "Host github_action_remote_machine\n\tUser eweb0124\n\tHostname 34.102.68.79\n\tIdentityFile ~/.ssh/github_actions_user_key_filename\n\tStrictHostKeyChecking No" >> ~/.ssh/config
      - run: scp -r ./nerfactory/viewer/app/build github_action_remote_machine:/home/eweb0124/viewer/build
      - run: ssn -n github_action_remote_machine mv /home/eweb0124/viewer/build /home/eweb0124/latest
